#
# Copyright (C) 2012 The CyanogenMod Project
# Copyright (C) 2012 The LiquidSmooth Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# inherit
-include vendor/samsung/toro/BoardConfigVendor.mk

# board
TARGET_BOARD_INFO_FILE ?= device/samsung/toro/board-info.txt

# include
include device/samsung/tuna/BoardConfig.mk

BOARD_USERDATAIMAGE_PARTITION_SIZE := 30691799040

# Use/add toro-specific variants
TARGET_RECOVERY_UPDATER_LIBS += librecovery_updater_toro
TARGET_RELEASETOOLS_EXTENSIONS := device/samsung/toro

# on toro boards we need to apply a special adaptive filter
# on the compass output because of noise generated by the pmic.
BOARD_INVENSENSE_APPLY_COMPASS_NOISE_FILTER := true

# kernel
TARGET_KERNEL_CUSTOM_TOOLCHAIN := linaro-4.7.2